/* Auto-generated from design-tokens.json — do not edit. */
export type ThemeName = 'dark' | 'light' | 'high-contrast';
export const DEFAULT_THEME: ThemeName = 'dark';
export const THEME_NAMES: readonly ThemeName[] = ["dark","light","high-contrast"];
export const TOKENS: Record<ThemeName, Readonly<Record<string, string>>> = {
  "dark": {
  "colors.primitive.void": "#000000",
  "colors.primitive.void-hover": "#0a0a0a",
  "colors.primitive.void-active": "#111111",
  "colors.primitive.panel": "#0d0d0d",
  "colors.primitive.panel-solid": "#0a0a0a",
  "colors.primitive.panel-hover": "#141414",
  "colors.primitive.border-dim": "#1a1a1a",
  "colors.primitive.border-default": "#2a2a2a",
  "colors.primitive.border-bright": "#3a3a3a",
  "colors.primitive.text-primary": "#e8e8e8",
  "colors.primitive.text-secondary": "#a0a0a0",
  "colors.primitive.text-dim": "#6a6a6a",
  "colors.primitive.text-inverse": "#000000",
  "colors.primitive.accent-cyan": "#00f3ff",
  "colors.primitive.accent-cyan-dim": "#00c5cc",
  "colors.primitive.accent-cyan-subtle": "#003d40",
  "colors.primitive.accent-magenta": "#ff00aa",
  "colors.primitive.accent-magenta-dim": "#cc0088",
  "colors.primitive.accent-amber": "#ffaa00",
  "colors.primitive.accent-amber-dim": "#cc8800",
  "colors.primitive.focus-ring": "#00f3ff",
  "colors.primitive.error": "#ff4444",
  "colors.primitive.warning": "#ffaa00",
  "colors.primitive.success": "#00cc88",
  "colors.primitive.info": "#00aaff",
  "colors.semantic.bg-base": "#000000",
  "colors.semantic.bg-panel": "#0d0d0d",
  "colors.semantic.bg-panel-solid": "#0a0a0a",
  "colors.semantic.bg-panel-hover": "#141414",
  "colors.semantic.bg-elevated": "#0a0a0a",
  "colors.semantic.border-subtle": "#1a1a1a",
  "colors.semantic.border-default": "#2a2a2a",
  "colors.semantic.border-focus": "#00f3ff",
  "colors.semantic.text-primary": "#e8e8e8",
  "colors.semantic.text-secondary": "#a0a0a0",
  "colors.semantic.text-muted": "#6a6a6a",
  "colors.semantic.text-on-accent": "#000000",
  "colors.semantic.status-connected": "#00cc88",
  "colors.semantic.status-connecting": "#00aaff",
  "colors.semantic.status-reconnecting": "#ffaa00",
  "colors.semantic.status-disconnected": "#ff4444",
  "colors.semantic.focus-ring": "#00f3ff",
  "colors.semantic.accent-primary": "#00f3ff",
  "colors.semantic.accent-primary-dim": "#00c5cc",
  "colors.semantic.accent-primary-subtle": "#003d40",
  "colors.cognitiveLens.belief.primary": "#00f3ff",
  "colors.cognitiveLens.belief.dim": "#00c5cc",
  "colors.cognitiveLens.belief.subtle": "#003d40",
  "colors.cognitiveLens.belief.bg": "#003d40",
  "colors.cognitiveLens.goal.primary": "#ff00aa",
  "colors.cognitiveLens.goal.dim": "#cc0088",
  "colors.cognitiveLens.goal.subtle": "rgba(255, 0, 170, 0.1)",
  "colors.cognitiveLens.goal.bg": "rgba(255, 0, 170, 0.1)",
  "colors.cognitiveLens.contradiction.primary": "#ffaa00",
  "colors.cognitiveLens.contradiction.dim": "#cc8800",
  "colors.cognitiveLens.contradiction.subtle": "rgba(255, 170, 0, 0.1)",
  "colors.cognitiveLens.contradiction.bg": "rgba(255, 170, 0, 0.1)",
  "colors.status.connected": "#00cc88",
  "colors.status.connecting": "#00aaff",
  "colors.status.reconnecting": "#ffaa00",
  "colors.status.disconnected": "#ff4444",
  "spacing.scale.0": "0",
  "spacing.scale.1": "2px",
  "spacing.scale.2": "4px",
  "spacing.scale.3": "8px",
  "spacing.scale.4": "12px",
  "spacing.scale.5": "16px",
  "spacing.scale.6": "24px",
  "spacing.scale.7": "32px",
  "spacing.scale.8": "48px",
  "spacing.scale.9": "64px",
  "spacing.component.panel-padding": "12px",
  "spacing.component.panel-gap": "8px",
  "spacing.component.button-padding-x": "8px",
  "spacing.component.button-padding-y": "2px",
  "spacing.component.input-padding-x": "8px",
  "spacing.component.input-padding-y": "4px",
  "spacing.component.toolbar-gap": "4px",
  "spacing.component.toolbar-padding": "8px",
  "spacing.component.tooltip-gap": "4px",
  "spacing.component.badge-gap": "2px",
  "typography.fontFamilies.ui": "\"IBM Plex Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  "typography.fontFamilies.data": "\"IBM Plex Mono\", \"SF Mono\", \"Fira Code\", monospace",
  "typography.fontFamilies.mono": "\"IBM Plex Mono\", monospace",
  "typography.scale.xs": "0.625rem",
  "typography.scale.sm": "0.75rem",
  "typography.scale.base": "0.875rem",
  "typography.scale.lg": "1rem",
  "typography.scale.xl": "1.125rem",
  "typography.scale.2xl": "1.25rem",
  "typography.scale.3xl": "1.5rem",
  "typography.lineHeights.tight": "1.2",
  "typography.lineHeights.normal": "1.5",
  "typography.lineHeights.relaxed": "1.75",
  "typography.fontWeights.normal": "400",
  "typography.fontWeights.medium": "500",
  "typography.fontWeights.semibold": "600",
  "typography.fontWeights.bold": "700",
  "motion.durations.instant": "0ms",
  "motion.durations.fast": "100ms",
  "motion.durations.normal": "200ms",
  "motion.durations.slow": "300ms",
  "motion.durations.slower": "500ms",
  "motion.easings.ease": "ease",
  "motion.easings.ease-in": "cubic-bezier(0.4, 0, 1, 1)",
  "motion.easings.ease-out": "cubic-bezier(0, 0, 0.2, 1)",
  "motion.easings.ease-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
  "motion.easings.spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
  "motion.reducedMotion.durations.fast": "0ms",
  "motion.reducedMotion.durations.normal": "0ms",
  "motion.reducedMotion.durations.slow": "0ms",
  "motion.reducedMotion.durations.slower": "0ms",
  "zIndex.layers.base": "0",
  "zIndex.layers.dropdown": "100",
  "zIndex.layers.tooltip": "200",
  "zIndex.layers.panel": "300",
  "zIndex.layers.modal": "400",
  "zIndex.layers.toast": "500",
  "zIndex.layers.palette": "600",
  "breakpoints.mobile": "640px",
  "breakpoints.tablet": "1024px",
  "breakpoints.desktop": "1280px",
  "breakpoints.wide": "1536px",
  "borderRadius.scale.none": "0",
  "borderRadius.scale.sm": "2px",
  "borderRadius.scale.md": "4px",
  "borderRadius.scale.lg": "8px",
  "borderRadius.scale.xl": "12px",
  "borderRadius.scale.full": "9999px",
  "borderRadius.component.button": "4px",
  "borderRadius.component.input": "4px",
  "borderRadius.component.panel": "8px",
  "borderRadius.component.tooltip": "2px",
  "borderRadius.component.badge": "9999px",
  "shadows.panel": "0 4px 16px rgba(0, 0, 0, 0.4)",
  "shadows.panel-hover": "0 8px 24px rgba(0, 0, 0, 0.5)",
  "shadows.modal": "0 16px 48px rgba(0, 0, 0, 0.6)",
  "shadows.tooltip": "0 2px 8px rgba(0, 0, 0, 0.4)",
  "shadows.focus": "0 0 0 3px #00f3ff",
  "transitions.fast": "100ms cubic-bezier(0, 0, 0.2, 1)",
  "transitions.normal": "200ms cubic-bezier(0, 0, 0.2, 1)",
  "transitions.slow": "300ms cubic-bezier(0, 0, 0.2, 1)"
},
  "light": {
  "colors.primitive.void": "#ffffff",
  "colors.primitive.void-hover": "#f5f5f5",
  "colors.primitive.void-active": "#eeeeee",
  "colors.primitive.panel": "#f7f7f7",
  "colors.primitive.panel-solid": "#ffffff",
  "colors.primitive.panel-hover": "#efefef",
  "colors.primitive.border-dim": "#e0e0e0",
  "colors.primitive.border-default": "#c4c4c4",
  "colors.primitive.border-bright": "#a8a8a8",
  "colors.primitive.text-primary": "#1a1a1a",
  "colors.primitive.text-secondary": "#444444",
  "colors.primitive.text-dim": "#767676",
  "colors.primitive.text-inverse": "#ffffff",
  "colors.primitive.accent-cyan": "#0088aa",
  "colors.primitive.accent-cyan-dim": "#006f88",
  "colors.primitive.accent-cyan-subtle": "#d0f0f5",
  "colors.primitive.accent-magenta": "#c4007f",
  "colors.primitive.accent-magenta-dim": "#9a0064",
  "colors.primitive.accent-amber": "#b36b00",
  "colors.primitive.accent-amber-dim": "#8a5300",
  "colors.primitive.focus-ring": "#0088aa",
  "colors.primitive.error": "#cc0000",
  "colors.primitive.warning": "#b36b00",
  "colors.primitive.success": "#00794d",
  "colors.primitive.info": "#0055aa",
  "colors.semantic.bg-base": "#ffffff",
  "colors.semantic.bg-panel": "#f7f7f7",
  "colors.semantic.bg-panel-solid": "#ffffff",
  "colors.semantic.bg-panel-hover": "#efefef",
  "colors.semantic.bg-elevated": "#f5f5f5",
  "colors.semantic.border-subtle": "#e0e0e0",
  "colors.semantic.border-default": "#c4c4c4",
  "colors.semantic.border-focus": "#0088aa",
  "colors.semantic.text-primary": "#1a1a1a",
  "colors.semantic.text-secondary": "#444444",
  "colors.semantic.text-muted": "#767676",
  "colors.semantic.text-on-accent": "#ffffff",
  "colors.semantic.status-connected": "#00794d",
  "colors.semantic.status-connecting": "#0055aa",
  "colors.semantic.status-reconnecting": "#b36b00",
  "colors.semantic.status-disconnected": "#cc0000",
  "colors.semantic.focus-ring": "#0088aa",
  "colors.semantic.accent-primary": "#0088aa",
  "colors.semantic.accent-primary-dim": "#006f88",
  "colors.semantic.accent-primary-subtle": "#d0f0f5",
  "colors.cognitiveLens.belief.primary": "#0088aa",
  "colors.cognitiveLens.belief.dim": "#006f88",
  "colors.cognitiveLens.belief.subtle": "#d0f0f5",
  "colors.cognitiveLens.belief.bg": "#d0f0f5",
  "colors.cognitiveLens.goal.primary": "#c4007f",
  "colors.cognitiveLens.goal.dim": "#9a0064",
  "colors.cognitiveLens.goal.subtle": "rgba(196, 0, 127, 0.1)",
  "colors.cognitiveLens.goal.bg": "rgba(196, 0, 127, 0.1)",
  "colors.cognitiveLens.contradiction.primary": "#b36b00",
  "colors.cognitiveLens.contradiction.dim": "#8a5300",
  "colors.cognitiveLens.contradiction.subtle": "rgba(179, 107, 0, 0.12)",
  "colors.cognitiveLens.contradiction.bg": "rgba(179, 107, 0, 0.12)",
  "colors.status.connected": "#00794d",
  "colors.status.connecting": "#0055aa",
  "colors.status.reconnecting": "#b36b00",
  "colors.status.disconnected": "#cc0000",
  "spacing.scale.0": "0",
  "spacing.scale.1": "2px",
  "spacing.scale.2": "4px",
  "spacing.scale.3": "8px",
  "spacing.scale.4": "12px",
  "spacing.scale.5": "16px",
  "spacing.scale.6": "24px",
  "spacing.scale.7": "32px",
  "spacing.scale.8": "48px",
  "spacing.scale.9": "64px",
  "spacing.component.panel-padding": "12px",
  "spacing.component.panel-gap": "8px",
  "spacing.component.button-padding-x": "8px",
  "spacing.component.button-padding-y": "2px",
  "spacing.component.input-padding-x": "8px",
  "spacing.component.input-padding-y": "4px",
  "spacing.component.toolbar-gap": "4px",
  "spacing.component.toolbar-padding": "8px",
  "spacing.component.tooltip-gap": "4px",
  "spacing.component.badge-gap": "2px",
  "typography.fontFamilies.ui": "\"IBM Plex Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  "typography.fontFamilies.data": "\"IBM Plex Mono\", \"SF Mono\", \"Fira Code\", monospace",
  "typography.fontFamilies.mono": "\"IBM Plex Mono\", monospace",
  "typography.scale.xs": "0.625rem",
  "typography.scale.sm": "0.75rem",
  "typography.scale.base": "0.875rem",
  "typography.scale.lg": "1rem",
  "typography.scale.xl": "1.125rem",
  "typography.scale.2xl": "1.25rem",
  "typography.scale.3xl": "1.5rem",
  "typography.lineHeights.tight": "1.2",
  "typography.lineHeights.normal": "1.5",
  "typography.lineHeights.relaxed": "1.75",
  "typography.fontWeights.normal": "400",
  "typography.fontWeights.medium": "500",
  "typography.fontWeights.semibold": "600",
  "typography.fontWeights.bold": "700",
  "motion.durations.instant": "0ms",
  "motion.durations.fast": "100ms",
  "motion.durations.normal": "200ms",
  "motion.durations.slow": "300ms",
  "motion.durations.slower": "500ms",
  "motion.easings.ease": "ease",
  "motion.easings.ease-in": "cubic-bezier(0.4, 0, 1, 1)",
  "motion.easings.ease-out": "cubic-bezier(0, 0, 0.2, 1)",
  "motion.easings.ease-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
  "motion.easings.spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
  "motion.reducedMotion.durations.fast": "0ms",
  "motion.reducedMotion.durations.normal": "0ms",
  "motion.reducedMotion.durations.slow": "0ms",
  "motion.reducedMotion.durations.slower": "0ms",
  "zIndex.layers.base": "0",
  "zIndex.layers.dropdown": "100",
  "zIndex.layers.tooltip": "200",
  "zIndex.layers.panel": "300",
  "zIndex.layers.modal": "400",
  "zIndex.layers.toast": "500",
  "zIndex.layers.palette": "600",
  "breakpoints.mobile": "640px",
  "breakpoints.tablet": "1024px",
  "breakpoints.desktop": "1280px",
  "breakpoints.wide": "1536px",
  "borderRadius.scale.none": "0",
  "borderRadius.scale.sm": "2px",
  "borderRadius.scale.md": "4px",
  "borderRadius.scale.lg": "8px",
  "borderRadius.scale.xl": "12px",
  "borderRadius.scale.full": "9999px",
  "borderRadius.component.button": "4px",
  "borderRadius.component.input": "4px",
  "borderRadius.component.panel": "8px",
  "borderRadius.component.tooltip": "2px",
  "borderRadius.component.badge": "9999px",
  "shadows.panel": "0 4px 16px rgba(0, 0, 0, 0.4)",
  "shadows.panel-hover": "0 8px 24px rgba(0, 0, 0, 0.5)",
  "shadows.modal": "0 16px 48px rgba(0, 0, 0, 0.6)",
  "shadows.tooltip": "0 2px 8px rgba(0, 0, 0, 0.4)",
  "shadows.focus": "0 0 0 3px #0088aa",
  "transitions.fast": "100ms cubic-bezier(0, 0, 0.2, 1)",
  "transitions.normal": "200ms cubic-bezier(0, 0, 0.2, 1)",
  "transitions.slow": "300ms cubic-bezier(0, 0, 0.2, 1)"
},
  "high-contrast": {
  "colors.primitive.void": "#000000",
  "colors.primitive.void-hover": "#0a0a0a",
  "colors.primitive.void-active": "#111111",
  "colors.primitive.panel": "#0d0d0d",
  "colors.primitive.panel-solid": "#0a0a0a",
  "colors.primitive.panel-hover": "#141414",
  "colors.primitive.border-dim": "#444444",
  "colors.primitive.border-default": "#6a6a6a",
  "colors.primitive.border-bright": "#8a8a8a",
  "colors.primitive.text-primary": "#ffffff",
  "colors.primitive.text-secondary": "#e0e0e0",
  "colors.primitive.text-dim": "#c0c0c0",
  "colors.primitive.text-inverse": "#000000",
  "colors.primitive.accent-cyan": "#5dfaff",
  "colors.primitive.accent-cyan-dim": "#3fd4dd",
  "colors.primitive.accent-cyan-subtle": "#00565c",
  "colors.primitive.accent-magenta": "#ff66cc",
  "colors.primitive.accent-magenta-dim": "#cc0088",
  "colors.primitive.accent-amber": "#ffd24d",
  "colors.primitive.accent-amber-dim": "#cc8800",
  "colors.primitive.focus-ring": "#5dfaff",
  "colors.primitive.error": "#ff7070",
  "colors.primitive.warning": "#ffd24d",
  "colors.primitive.success": "#4dffb0",
  "colors.primitive.info": "#66ccff",
  "colors.semantic.bg-base": "#000000",
  "colors.semantic.bg-panel": "#0d0d0d",
  "colors.semantic.bg-panel-solid": "#0a0a0a",
  "colors.semantic.bg-panel-hover": "#141414",
  "colors.semantic.bg-elevated": "#0a0a0a",
  "colors.semantic.border-subtle": "#444444",
  "colors.semantic.border-default": "#6a6a6a",
  "colors.semantic.border-focus": "#5dfaff",
  "colors.semantic.text-primary": "#ffffff",
  "colors.semantic.text-secondary": "#e0e0e0",
  "colors.semantic.text-muted": "#c0c0c0",
  "colors.semantic.text-on-accent": "#000000",
  "colors.semantic.status-connected": "#4dffb0",
  "colors.semantic.status-connecting": "#66ccff",
  "colors.semantic.status-reconnecting": "#ffd24d",
  "colors.semantic.status-disconnected": "#ff7070",
  "colors.semantic.focus-ring": "#5dfaff",
  "colors.semantic.accent-primary": "#5dfaff",
  "colors.semantic.accent-primary-dim": "#3fd4dd",
  "colors.semantic.accent-primary-subtle": "#00565c",
  "colors.cognitiveLens.belief.primary": "#5dfaff",
  "colors.cognitiveLens.belief.dim": "#3fd4dd",
  "colors.cognitiveLens.belief.subtle": "#00565c",
  "colors.cognitiveLens.belief.bg": "#00565c",
  "colors.cognitiveLens.goal.primary": "#ff66cc",
  "colors.cognitiveLens.goal.dim": "#cc0088",
  "colors.cognitiveLens.goal.subtle": "rgba(255, 0, 170, 0.1)",
  "colors.cognitiveLens.goal.bg": "rgba(255, 0, 170, 0.1)",
  "colors.cognitiveLens.contradiction.primary": "#ffd24d",
  "colors.cognitiveLens.contradiction.dim": "#cc8800",
  "colors.cognitiveLens.contradiction.subtle": "rgba(255, 170, 0, 0.1)",
  "colors.cognitiveLens.contradiction.bg": "rgba(255, 170, 0, 0.1)",
  "colors.status.connected": "#4dffb0",
  "colors.status.connecting": "#66ccff",
  "colors.status.reconnecting": "#ffd24d",
  "colors.status.disconnected": "#ff7070",
  "spacing.scale.0": "0",
  "spacing.scale.1": "2px",
  "spacing.scale.2": "4px",
  "spacing.scale.3": "8px",
  "spacing.scale.4": "12px",
  "spacing.scale.5": "16px",
  "spacing.scale.6": "24px",
  "spacing.scale.7": "32px",
  "spacing.scale.8": "48px",
  "spacing.scale.9": "64px",
  "spacing.component.panel-padding": "12px",
  "spacing.component.panel-gap": "8px",
  "spacing.component.button-padding-x": "8px",
  "spacing.component.button-padding-y": "2px",
  "spacing.component.input-padding-x": "8px",
  "spacing.component.input-padding-y": "4px",
  "spacing.component.toolbar-gap": "4px",
  "spacing.component.toolbar-padding": "8px",
  "spacing.component.tooltip-gap": "4px",
  "spacing.component.badge-gap": "2px",
  "typography.fontFamilies.ui": "\"IBM Plex Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  "typography.fontFamilies.data": "\"IBM Plex Mono\", \"SF Mono\", \"Fira Code\", monospace",
  "typography.fontFamilies.mono": "\"IBM Plex Mono\", monospace",
  "typography.scale.xs": "0.625rem",
  "typography.scale.sm": "0.75rem",
  "typography.scale.base": "0.875rem",
  "typography.scale.lg": "1rem",
  "typography.scale.xl": "1.125rem",
  "typography.scale.2xl": "1.25rem",
  "typography.scale.3xl": "1.5rem",
  "typography.lineHeights.tight": "1.2",
  "typography.lineHeights.normal": "1.5",
  "typography.lineHeights.relaxed": "1.75",
  "typography.fontWeights.normal": "400",
  "typography.fontWeights.medium": "500",
  "typography.fontWeights.semibold": "600",
  "typography.fontWeights.bold": "700",
  "motion.durations.instant": "0ms",
  "motion.durations.fast": "100ms",
  "motion.durations.normal": "200ms",
  "motion.durations.slow": "300ms",
  "motion.durations.slower": "500ms",
  "motion.easings.ease": "ease",
  "motion.easings.ease-in": "cubic-bezier(0.4, 0, 1, 1)",
  "motion.easings.ease-out": "cubic-bezier(0, 0, 0.2, 1)",
  "motion.easings.ease-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
  "motion.easings.spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
  "motion.reducedMotion.durations.fast": "0ms",
  "motion.reducedMotion.durations.normal": "0ms",
  "motion.reducedMotion.durations.slow": "0ms",
  "motion.reducedMotion.durations.slower": "0ms",
  "zIndex.layers.base": "0",
  "zIndex.layers.dropdown": "100",
  "zIndex.layers.tooltip": "200",
  "zIndex.layers.panel": "300",
  "zIndex.layers.modal": "400",
  "zIndex.layers.toast": "500",
  "zIndex.layers.palette": "600",
  "breakpoints.mobile": "640px",
  "breakpoints.tablet": "1024px",
  "breakpoints.desktop": "1280px",
  "breakpoints.wide": "1536px",
  "borderRadius.scale.none": "0",
  "borderRadius.scale.sm": "2px",
  "borderRadius.scale.md": "4px",
  "borderRadius.scale.lg": "8px",
  "borderRadius.scale.xl": "12px",
  "borderRadius.scale.full": "9999px",
  "borderRadius.component.button": "4px",
  "borderRadius.component.input": "4px",
  "borderRadius.component.panel": "8px",
  "borderRadius.component.tooltip": "2px",
  "borderRadius.component.badge": "9999px",
  "shadows.panel": "0 4px 16px rgba(0, 0, 0, 0.4)",
  "shadows.panel-hover": "0 8px 24px rgba(0, 0, 0, 0.5)",
  "shadows.modal": "0 16px 48px rgba(0, 0, 0, 0.6)",
  "shadows.tooltip": "0 2px 8px rgba(0, 0, 0, 0.4)",
  "shadows.focus": "0 0 0 3px #5dfaff",
  "transitions.fast": "100ms cubic-bezier(0, 0, 0.2, 1)",
  "transitions.normal": "200ms cubic-bezier(0, 0, 0.2, 1)",
  "transitions.slow": "300ms cubic-bezier(0, 0, 0.2, 1)"
},
};
