// Auto-generated from design-tokens.json
export const tokens = {
    colors_primitive_void: '#000000' as const,
    'colors_primitive_void-hover': '#0a0a0a' as const,
    'colors_primitive_void-active': '#111111' as const,
    colors_primitive_panel: '#0d0d0d' as const,
    'colors_primitive_panel-solid': '#0a0a0a' as const,
    'colors_primitive_panel-hover': '#141414' as const,
    'colors_primitive_border-dim': '#1a1a1a' as const,
    'colors_primitive_border-default': '#2a2a2a' as const,
    'colors_primitive_border-bright': '#3a3a3a' as const,
    'colors_primitive_text-primary': '#e8e8e8' as const,
    'colors_primitive_text-secondary': '#a0a0a0' as const,
    'colors_primitive_text-dim': '#6a6a6a' as const,
    'colors_primitive_text-inverse': '#000000' as const,
    'colors_primitive_accent-cyan': '#00f3ff' as const,
    'colors_primitive_accent-cyan-dim': '#00c5cc' as const,
    'colors_primitive_accent-cyan-subtle': '#003d40' as const,
    'colors_primitive_accent-magenta': '#ff00aa' as const,
    'colors_primitive_accent-magenta-dim': '#cc0088' as const,
    'colors_primitive_accent-amber': '#ffaa00' as const,
    'colors_primitive_accent-amber-dim': '#cc8800' as const,
    'colors_primitive_focus-ring': '#00f3ff' as const,
    colors_primitive_error: '#ff4444' as const,
    colors_primitive_warning: '#ffaa00' as const,
    colors_primitive_success: '#00cc88' as const,
    colors_primitive_info: '#00aaff' as const,
    'colors_semantic_bg-base': '#000000' as const,
    'colors_semantic_bg-panel': '#0d0d0d' as const,
    'colors_semantic_bg-panel-solid': '#0a0a0a' as const,
    'colors_semantic_bg-panel-hover': '#141414' as const,
    'colors_semantic_bg-elevated': '#0a0a0a' as const,
    'colors_semantic_border-subtle': '#1a1a1a' as const,
    'colors_semantic_border-default': '#2a2a2a' as const,
    'colors_semantic_border-focus': '#00f3ff' as const,
    'colors_semantic_text-primary': '#e8e8e8' as const,
    'colors_semantic_text-secondary': '#a0a0a0' as const,
    'colors_semantic_text-muted': '#6a6a6a' as const,
    'colors_semantic_text-on-accent': '#000000' as const,
    'colors_semantic_status-connected': '#00cc88' as const,
    'colors_semantic_status-connecting': '#00aaff' as const,
    'colors_semantic_status-reconnecting': '#ffaa00' as const,
    'colors_semantic_status-disconnected': '#ff4444' as const,
    'colors_semantic_focus-ring': '#00f3ff' as const,
    'colors_semantic_accent-primary': '#00f3ff' as const,
    'colors_semantic_accent-primary-dim': '#00c5cc' as const,
    'colors_semantic_accent-primary-subtle': '#003d40' as const,
    colors_cognitiveLens_belief_primary: '#00f3ff' as const,
    colors_cognitiveLens_belief_dim: '#00c5cc' as const,
    colors_cognitiveLens_belief_subtle: '#003d40' as const,
    colors_cognitiveLens_belief_bg: '#003d40' as const,
    colors_cognitiveLens_goal_primary: '#ff00aa' as const,
    colors_cognitiveLens_goal_dim: '#cc0088' as const,
    colors_cognitiveLens_goal_subtle: 'rgba(255, 0, 170, 0.1)' as const,
    colors_cognitiveLens_goal_bg: 'rgba(255, 0, 170, 0.1)' as const,
    colors_cognitiveLens_contradiction_primary: '#ffaa00' as const,
    colors_cognitiveLens_contradiction_dim: '#cc8800' as const,
    colors_cognitiveLens_contradiction_subtle: 'rgba(255, 170, 0, 0.1)' as const,
    colors_cognitiveLens_contradiction_bg: 'rgba(255, 170, 0, 0.1)' as const,
    colors_status_connected: '#00cc88' as const,
    colors_status_connecting: '#00aaff' as const,
    colors_status_reconnecting: '#ffaa00' as const,
    colors_status_disconnected: '#ff4444' as const,
    spacing_scale_0: '0' as const,
    spacing_scale_1: '2px' as const,
    spacing_scale_2: '4px' as const,
    spacing_scale_3: '8px' as const,
    spacing_scale_4: '12px' as const,
    spacing_scale_5: '16px' as const,
    spacing_scale_6: '24px' as const,
    spacing_scale_7: '32px' as const,
    spacing_scale_8: '48px' as const,
    spacing_scale_9: '64px' as const,
    'spacing_component_panel-padding': '12px' as const,
    'spacing_component_panel-gap': '8px' as const,
    'spacing_component_button-padding-x': '8px' as const,
    'spacing_component_button-padding-y': '2px' as const,
    'spacing_component_input-padding-x': '8px' as const,
    'spacing_component_input-padding-y': '4px' as const,
    'spacing_component_toolbar-gap': '4px' as const,
    'spacing_component_toolbar-padding': '8px' as const,
    'spacing_component_tooltip-gap': '4px' as const,
    'spacing_component_badge-gap': '2px' as const,
    typography_fontFamilies_ui:
        '"IBM Plex Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' as const,
    typography_fontFamilies_data: '"IBM Plex Mono", "SF Mono", "Fira Code", monospace' as const,
    typography_fontFamilies_mono: '"IBM Plex Mono", monospace' as const,
    typography_scale_xs: '0.625rem' as const,
    typography_scale_sm: '0.75rem' as const,
    typography_scale_base: '0.875rem' as const,
    typography_scale_lg: '1rem' as const,
    typography_scale_xl: '1.125rem' as const,
    typography_scale_2xl: '1.25rem' as const,
    typography_scale_3xl: '1.5rem' as const,
    typography_lineHeights_tight: '1.2' as const,
    typography_lineHeights_normal: '1.5' as const,
    typography_lineHeights_relaxed: '1.75' as const,
    typography_fontWeights_normal: '400' as const,
    typography_fontWeights_medium: '500' as const,
    typography_fontWeights_semibold: '600' as const,
    typography_fontWeights_bold: '700' as const,
    motion_durations_instant: '0ms' as const,
    motion_durations_fast: '100ms' as const,
    motion_durations_normal: '200ms' as const,
    motion_durations_slow: '300ms' as const,
    motion_durations_slower: '500ms' as const,
    motion_easings_ease: 'ease' as const,
    'motion_easings_ease-in': 'cubic-bezier(0.4, 0, 1, 1)' as const,
    'motion_easings_ease-out': 'cubic-bezier(0, 0, 0.2, 1)' as const,
    'motion_easings_ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)' as const,
    motion_easings_spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' as const,
    motion_reducedMotion_durations_fast: '0ms' as const,
    motion_reducedMotion_durations_normal: '0ms' as const,
    motion_reducedMotion_durations_slow: '0ms' as const,
    motion_reducedMotion_durations_slower: '0ms' as const,
    zIndex_layers_base: '0' as const,
    zIndex_layers_dropdown: '100' as const,
    zIndex_layers_tooltip: '200' as const,
    zIndex_layers_panel: '300' as const,
    zIndex_layers_modal: '400' as const,
    zIndex_layers_toast: '500' as const,
    zIndex_layers_palette: '600' as const,
    breakpoints_mobile: '640px' as const,
    breakpoints_tablet: '1024px' as const,
    breakpoints_desktop: '1280px' as const,
    breakpoints_wide: '1536px' as const,
    borderRadius_scale_none: '0' as const,
    borderRadius_scale_sm: '2px' as const,
    borderRadius_scale_md: '4px' as const,
    borderRadius_scale_lg: '8px' as const,
    borderRadius_scale_xl: '12px' as const,
    borderRadius_scale_full: '9999px' as const,
    borderRadius_component_button: '4px' as const,
    borderRadius_component_input: '4px' as const,
    borderRadius_component_panel: '8px' as const,
    borderRadius_component_tooltip: '2px' as const,
    borderRadius_component_badge: '9999px' as const,
    shadows_panel: '0 4px 16px rgba(0, 0, 0, 0.4)' as const,
    'shadows_panel-hover': '0 8px 24px rgba(0, 0, 0, 0.5)' as const,
    shadows_modal: '0 16px 48px rgba(0, 0, 0, 0.6)' as const,
    shadows_tooltip: '0 2px 8px rgba(0, 0, 0, 0.4)' as const,
    shadows_focus: '0 0 0 3px #00f3ff' as const,
    transitions_fast: '100ms cubic-bezier(0, 0, 0.2, 1)' as const,
    transitions_normal: '200ms cubic-bezier(0, 0, 0.2, 1)' as const,
    transitions_slow: '300ms cubic-bezier(0, 0, 0.2, 1)' as const,
} as const;

export type TokenPath = keyof typeof tokens;
