/**
 * README.md is generated from the sections in this directory.
 *
 * It was one 1753-line file that every change to the system touched, and it
 * drifted in two directions at once: prose no reviewer could read in a diff, and
 * projections — the NAL rule matrix — hand-maintained mirrors of a table the
 * engine already knows. So the prose lives here, one file per heading, and this
 * generator owns the two things a section file must not: the order, and every
 * value that is a projection of something else.
 *
 * A section file is its heading and its body. The `---` between top-level
 * sections is emitted here, a section's level is read from its own heading, and
 * `<!-- name -->` is a directive replaced by the generator that owns it. The rest
 * is gates — a section not in `ORDER`, a link that does not resolve, a
 * `pnpm <script>` package.json no longer declares — because each of those is a
 * README that is wrong in a way no reviewer can see.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { BUILTIN_DECLARATIONS } from '../../nar/src/rules/impls/registration.js';
import { fromRoot } from '../../scripts/lib/root.js';

const DIR = fromRoot('docs/readme');
const README = fromRoot('README.md');

const BANNER = '<!-- generated by docs/readme/generate.ts — do not edit -->';

/** The one section named for the document rather than for a heading it contains. */
const TITLE = 'overview.md';

/** The README's order. A section's heading says what level it is; this says where it goes. */
const ORDER = [
  'overview.md',
  'run.md',
  'the-trusted-cognitive-kernel.md',
  'kernel-gates-trusted-boundary.md',
  'event-sourcing-provenance.md',
  'source-quality-grounding.md',
  'implementation-philosophy-type-driven-invariants.md',
  'the-core-and-the-induction-layer.md',
  'cognitive-architecture-aikr.md',
  'inference.md',
  'narsese-term-language.md',
  'truth-value-algebra.md',
  'nal-inference-rules.md',
  'reasoning.md',
  'derivation-ranking-pressure-valve.md',
  'metta-exact-computation-substrate.md',
  'neuro-symbolic-integration.md',
  'dynamic-neuro-symbolic-fusion.md',
  'multi-agent-cognitive-cooperation.md',
  'natural-language-services.md',
  'local-inference-llama-cpp.md',
  'system-one-the-judgment-manifold.md',
  'live-ingress.md',
  'cortex-ladder.md',
  'heads-digests-calibration.md',
  'distillation-flywheel.md',
  'dialogue-flywheel.md',
  'rl-without-nal.md',
  'remote-manifold.md',
  'observability-ux.md',
  'arcade-multi-game-system-one-demo.md',
  'execution-control.md',
  'stream-reasoner.md',
  'tools-function-calling.md',
  'nar-commands-cli-programmatic-control.md',
  'cognitive-parameters-strategy-system.md',
  'cognitive-control-metacognition.md',
  'senars-as-a-general-purpose-rl-agent.md',
  'rlfp-reinforcement-learning-from-reasoning-feedback.md',
  'self-improvement-loop.md',
  'architecture.md',
  'self-concept-vocabulary.md',
  'meta-rules-with-aikr-bounds-5-rules.md',
  'homeostatic-drives-4-drives.md',
  'self-modification-governance.md',
  'ecosystem-integration-layer.md',
  'core-agent-runtime-senars-core.md',
  'multi-transport-agent-the-bot.md',
  'api-layer.md',
  'web-ui-visualization.md',
  'ui-gallery.md',
  'safety-observability-governance.md',
  'configuration-reference.md',
  'proof-obligations-benchmark-plan.md',
  'reference.md',
  'license.md',
] as const;

/**
 * The README's rule matrix, generated from the loaded table.
 *
 * It was transcribed, and it had already drifted: `nar.extended.exemplification`
 * was listed twice, `nal.higherOrderDeduction` and `nal.contrapositionRule` do not
 * exist under those ids, and the "Meta-Cognitive — none" row described a category
 * with no members. A hand-maintained list of a generated table is the second
 * source of truth §11.1 names, and this closes it: the matrix is a projection of
 * `BUILTIN_DECLARATIONS`, so a rule cannot be added, renamed or removed without
 * the README changing in the same commit — and `pnpm readme:check` fails if it does.
 *
 * Rows are **dispatch cells** — the pattern pair a rule declares — because that is
 * what dispatch actually keys on (TODO29.a §5.6) and it is the one grouping the
 * table can be wrong about. The transcribed version grouped by a category word that
 * existed nowhere in the code, which is why two of its rows were aspirational and
 * one listed a rule twice.
 */
export const renderMatrix = (
  declarations: readonly {
    ruleId: string;
    left: { op: string };
    right: { op: string };
    truthFn: string;
  }[]
): string => {
  const cells = new Map<string, string[]>();
  for (const declaration of declarations) {
    const cell = `\`${declaration.left.op}:${declaration.right.op}\``;
    cells.set(cell, [
      ...(cells.get(cell) ?? []),
      `\`${declaration.ruleId}\` (${declaration.truthFn})`,
    ]);
  }
  const rows = [...cells]
    .sort(([a], [b]) => b.length - a.length || a.localeCompare(b))
    .map(([cell, rules]) => `| ${cell} | ${rules.length} | ${rules.join(', ')} |`);
  return [
    '| Dispatch cell | Rules | Declarations |',
    '|---|---|---|',
    ...rows,
    '',
    `_${declarations.length} declarations in ${cells.size} cells, loaded at revision 0 with ` +
      '`artifactVersion` `builtin/1`. Every cell is an exact kind pair: a rule declares both ' +
      'kinds or it does not register, and `pnpm dispatch:no-wildcard` is the gate._',
  ].join('\n');
};

/** Directives a section file may carry, each replaced by the generator that owns it. */
const TEMPLATES: Readonly<Record<string, () => string>> = {
  'rule-matrix': () => renderMatrix(BUILTIN_DECLARATIONS),
};

/** `pnpm`'s own verbs — a `pnpm <verb>` reference that names none of these must be a script. */
const PNPM_VERBS = new Set([
  'add',
  'approve-build',
  'audit',
  'create',
  'dedupe',
  'dlx',
  'exec',
  'i',
  'import',
  'install',
  'licenses',
  'link',
  'out',
  'outdated',
  'pack',
  'patch',
  'prune',
  'publish',
  'remove',
  'root',
  'run',
  'store',
  'uninstall',
  'update',
  'why',
]);

interface Violation {
  readonly at: string;
  readonly rule: string;
  readonly detail: string;
}

interface Section {
  readonly file: string;
  readonly level: number;
  readonly heading: string;
  readonly body: string;
}

const slugify = (heading: string): string =>
  heading
    .replace(/[`*]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const readSection = (file: string): Section => {
  const [first = '', ...rest] = readFileSync(join(DIR, file), 'utf8').trimEnd().split('\n');
  const heading = /^(#{1,6}) (.+)$/.exec(first);
  if (!heading?.[2]) throw new Error(`${file} does not open with a markdown heading`);
  return {
    file,
    level: heading[1]?.length ?? 1,
    heading: heading[2],
    body: rest.join('\n').trim(),
  };
};

const sections = (): Section[] => ORDER.map(readSection);

/** A section as the README renders it: its heading, its body, every directive resolved. */
const renderSection = (section: Section): string =>
  `${'#'.repeat(section.level)} ${section.heading}${section.body ? `\n\n${section.body}` : ''}`.replace(
    /^<!-- ([a-z][\w-]*) -->$/gm,
    (_directive, name: string) => {
      const template = TEMPLATES[name];
      if (!template) throw new Error(`${section.file}: no template named '${name}'`);
      return template();
    }
  );

/** The composed README: banner, then each section, `---` between the top-level ones. */
export const buildReadme = (): string => {
  const ordered = sections();
  const blocks: string[] = [];
  for (const [index, section] of ordered.entries()) {
    if (index > 0 && section.level <= 2) blocks.push('---');
    blocks.push(renderSection(section));
  }
  return `${[BANNER, ...blocks].join('\n\n')}\n`;
};

const sectionViolations = (): Violation[] => {
  const violations: Violation[] = [];
  const listed = new Set<string>(ORDER);
  for (const file of readdirSync(DIR)) {
    if (file.endsWith('.md') && !listed.has(file)) {
      violations.push({ at: file, rule: 'orphaned-section', detail: 'not in ORDER' });
    }
  }
  let level = 0;
  for (const file of ORDER) {
    if (!existsSync(join(DIR, file))) {
      violations.push({ at: file, rule: 'missing-section', detail: 'in ORDER, absent on disk' });
      continue;
    }
    const section = readSection(file);
    const expected = file === TITLE ? section.file : `${slugify(section.heading)}.md`;
    if (expected !== file) {
      violations.push({
        at: file,
        rule: 'section-name',
        detail: `'${section.heading}' belongs in ${expected}`,
      });
    }
    if (section.level > level + 1) {
      violations.push({
        at: file,
        rule: 'heading-level',
        detail: `h${section.level} under h${level} — a section may not skip a level`,
      });
    }
    level = section.level;
  }
  return violations;
};

const linkViolations = (markdown: string): Violation[] =>
  [...markdown.matchAll(/\]\(([^)\s]+?)(?:\s+"[^"]*")?\)/g)]
    .map((match) => match[1] ?? '')
    .filter((href) => href !== '' && !/^[a-z][\w+.-]*:/i.test(href) && !href.startsWith('#'))
    .filter((href) => !existsSync(fromRoot(decodeURIComponent(href.split('#')[0] ?? ''))))
    .map((href) => ({ at: 'README.md', rule: 'dead-link', detail: href }));

const scriptViolations = (markdown: string): Violation[] => {
  const scripts = new Set(
    Object.keys(JSON.parse(readFileSync(fromRoot('package.json'), 'utf8')).scripts ?? {})
  );
  return [...markdown.matchAll(/\bpnpm\s+(?:run\s+)?([a-zA-Z][\w:.-]*)/g)]
    .map((match) => match[1] ?? '')
    .filter((name) => !name.startsWith('-') && !name.startsWith('.') && !PNPM_VERBS.has(name))
    .filter((name) => !scripts.has(name))
    .map((name) => ({ at: 'README.md', rule: 'unknown-script', detail: `pnpm ${name}` }));
};

const firstDifference = (current: string, next: string): number => {
  const a = current.split('\n');
  const b = next.split('\n');
  const index = a.findIndex((line, at) => line !== b[at]);
  return index < 0 ? Math.min(a.length, b.length) + 1 : index + 1;
};

const report = (violations: readonly Violation[]): never => {
  console.error(`readme FAILED — ${violations.length} violation(s)`);
  for (const { at, rule, detail } of violations) console.error(`  ${at}: ${rule} — ${detail}`);
  process.exit(1);
};

const main = (): void => {
  const structural = sectionViolations();
  if (structural.length > 0) report(structural);

  const next = buildReadme();
  const content = [...linkViolations(next), ...scriptViolations(next)];
  if (content.length > 0) report(content);

  const current = readFileSync(README, 'utf8');
  if (current === next) {
    console.log(
      `readme ok — ${ORDER.length} sections · ${BUILTIN_DECLARATIONS.length} rule declarations`
    );
    return;
  }
  if (process.argv.includes('--check')) {
    console.error(
      `readme:check FAILED — README.md differs from the sections at line ${firstDifference(current, next)}; run \`pnpm readme\``
    );
    process.exit(1);
  }
  writeFileSync(README, next);
  console.log(
    `readme — README.md ${ORDER.length} sections, ${next.split('\n').length} lines · ${BUILTIN_DECLARATIONS.length} rule declarations`
  );
};

if (process.argv[1]?.endsWith('generate.ts')) main();
