import {
  AnalogySchema,
  BeliefRevisionSchema,
  ConceptElaborationSchema,
  ExplanationSchema,
  HypothesisSchema,
  MetaReasoningSchema,
  SchemaInductionSchema,
  TemporalCausalSchema,
  TranslationSchema,
  UncertaintySchema,
  VariableGroundingSchema,
} from '../../nl';
/**
 * Belief-oriented LM rule definitions.
 */
import type { LMRuleDefinition } from '../rule-builders.js';
import { symbolicFallbacks } from './fallbacks.js';
import { hasConflictingBeliefs, hasLowConfidence } from '../rule-selectors/confidence.js';
import {
  hasStructuralSimilarityNoOverlap,
  isUnderconnected,
} from '../rule-selectors/connectivity.js';
import { hasVariable } from '../rule-selectors/factory.js';

export const beliefRules: LMRuleDefinition[] = [
  {
    id: 'lm-narsese-translation',
    name: 'LMNarseseTranslationRule',
    description: 'Translates natural language to Narsese',
    priority: 0.9,
    taskType: 'belief',
    budget: 0.9,
    schema: TranslationSchema,
    fallback: symbolicFallbacks['lm-narsese-translation'],
    maxOutputTokens: 64,
  },
  {
    id: 'lm-belief-revision',
    name: 'LMBeliefRevisionRule',
    description: 'Revises belief confidence based on context',
    priority: 0.8,
    taskType: 'belief',
    budget: 0.7,
    activationCondition: hasConflictingBeliefs,
    schema: BeliefRevisionSchema,
    constitutionAware: true,
    fallback: symbolicFallbacks['lm-belief-revision'],
    maxOutputTokens: 64,
  },
  {
    id: 'lm-hypothesis-generation',
    name: 'LMHypothesisGenerationRule',
    description: 'Generates hypotheses from observations',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.6,
    activationCondition: hasLowConfidence,
    schema: HypothesisSchema,
    enableTools: true,
    constitutionAware: true,
    grammar: 'narsese-term',
    fallback: symbolicFallbacks['lm-hypothesis-generation'],
    maxOutputTokens: 128,
  },
  {
    id: 'lm-explanation-generation',
    name: 'LMExplanationGenerationRule',
    description: 'Generates explanations for beliefs',
    priority: 0.7,
    taskType: 'belief',
    budget: 0.65,
    schema: ExplanationSchema,
    fallback: symbolicFallbacks['lm-explanation-generation'],
    maxOutputTokens: 128,
  },
  {
    id: 'lm-analogical-reasoning',
    name: 'LMAnalogicalReasoningRule',
    description: 'Performs analogical reasoning between concepts',
    priority: 0.8,
    taskType: 'belief',
    budget: 0.7,
    activationCondition: hasStructuralSimilarityNoOverlap,
    schema: AnalogySchema,
    enableTools: true,
    grammar: 'single-word',
    maxOutputTokens: 8,
    fallback: symbolicFallbacks['lm-analogical-reasoning'],
  },
  {
    id: 'lm-meta-reasoning',
    name: 'LMMetaReasoningGuidanceRule',
    description: 'Provides meta-level reasoning guidance',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.65,
    schema: MetaReasoningSchema,
    fallback: symbolicFallbacks['lm-meta-reasoning'],
    maxOutputTokens: 64,
  },
  {
    id: 'lm-uncertainty-calibration',
    name: 'LMUncertaintyCalibrationRule',
    description: 'Calibrates uncertainty in beliefs',
    priority: 0.7,
    taskType: 'belief',
    budget: 0.6,
    schema: UncertaintySchema,
    maxOutputTokens: 64,
  },
  {
    id: 'lm-schema-induction',
    name: 'LMSchemaInductionRule',
    description: 'Induces schemas from examples',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.65,
    schema: SchemaInductionSchema,
    fallback: symbolicFallbacks['lm-schema-induction'],
    maxOutputTokens: 256,
  },
  {
    id: 'lm-temporal-causal',
    name: 'LMTemporalCausalModelingRule',
    description: 'Models temporal and causal relationships',
    priority: 0.8,
    taskType: 'belief',
    budget: 0.7,
    schema: TemporalCausalSchema,
    maxOutputTokens: 128,
  },
  {
    id: 'lm-variable-grounding',
    name: 'LMVariableGroundingRule',
    description: 'Grounds variables in concrete instances',
    priority: 0.7,
    taskType: 'belief',
    budget: 0.65,
    activationCondition: (p) => hasVariable(p),
    schema: VariableGroundingSchema,
    maxOutputTokens: 128,
  },
  {
    id: 'lm-concept-elaboration',
    name: 'LMConceptElaborationRule',
    description: 'Elaborates on concept properties',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.7,
    activationCondition: isUnderconnected,
    schema: ConceptElaborationSchema,
    maxOutputTokens: 256,
  },
];
