/**
 * Belief-oriented LM rule definitions.
 */
import type { LMRuleDefinition } from '../rule-builders.js';
import { hasConflictingBeliefs, hasLowConfidence } from '../rule-selectors/confidence.js';
import {
  hasStructuralSimilarityNoOverlap,
  isUnderconnected,
} from '../rule-selectors/connectivity.js';
import { hasVariable } from '../rule-selectors/factory.js';
import { symbolicFallbacks } from './fallbacks.js';
import {
  AnalogySchema,
  BeliefRevisionSchema,
  ConceptElaborationSchema,
  ExplanationSchema,
  HypothesisSchema,
  MetaReasoningSchema,
  SchemaInductionSchema,
  TemporalCausalSchema,
  TranslationSchema,
  UncertaintySchema,
  VariableGroundingSchema,
} from './schemas.js';

export const beliefRules: LMRuleDefinition[] = [
  {
    id: 'lm-narsese-translation',
    prompt: 'Translate the following sentence into Narsese logic. Sentence: "{{taskTerm}}"',
    name: 'LMNarseseTranslationRule',
    description: 'Translates natural language to Narsese',
    priority: 0.9,
    taskType: 'belief',
    budget: 0.9,
    schema: TranslationSchema,
    fallback: symbolicFallbacks['lm-narsese-translation'],
    maxOutputTokens: 64,
  },
  {
    id: 'lm-belief-revision',
    prompt: 'Given "{{primaryTerm}}", should its confidence be revised?',
    name: 'LMBeliefRevisionRule',
    description: 'Revises belief confidence based on context',
    priority: 0.8,
    taskType: 'belief',
    budget: 0.7,
    activationCondition: hasConflictingBeliefs,
    schema: BeliefRevisionSchema,
    constitutionAware: true,
    fallback: symbolicFallbacks['lm-belief-revision'],
    maxOutputTokens: 64,
  },
  {
    id: 'lm-hypothesis-generation',
    prompt: 'Given "{{primaryTerm}}", what are possible explanations?',
    name: 'LMHypothesisGenerationRule',
    description: 'Generates hypotheses from observations',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.6,
    activationCondition: hasLowConfidence,
    schema: HypothesisSchema,
    enableTools: true,
    constitutionAware: true,
    grammar: 'narsese-term',
    fallback: symbolicFallbacks['lm-hypothesis-generation'],
    maxOutputTokens: 128,
  },
  {
    id: 'lm-explanation-generation',
    prompt: 'Complete this sentence naturally, under 20 words: "I believe {{primaryTerm}} because {{premise1}} and {{premise2}}."',
    name: 'LMExplanationGenerationRule',
    description: 'Generates explanations for beliefs',
    priority: 0.7,
    taskType: 'belief',
    budget: 0.65,
    schema: ExplanationSchema,
    fallback: symbolicFallbacks['lm-explanation-generation'],
    maxOutputTokens: 128,
  },
  {
    id: 'lm-analogical-reasoning',
    prompt: 'Concept A is "{{primaryTerm}}". Concept B is "{{premise1}}". Concept X is "{{secondaryTerm}}". Concept Y is "[MASK]". Fill the mask with exactly one word.',
    name: 'LMAnalogicalReasoningRule',
    description: 'Performs analogical reasoning between concepts',
    priority: 0.8,
    taskType: 'belief',
    budget: 0.7,
    activationCondition: hasStructuralSimilarityNoOverlap,
    schema: AnalogySchema,
    enableTools: true,
    grammar: 'single-word',
    maxOutputTokens: 8,
    fallback: symbolicFallbacks['lm-analogical-reasoning'],
  },
  {
    id: 'lm-meta-reasoning',
    prompt: 'Analyze the reasoning for "{{primaryTerm}}".',
    name: 'LMMetaReasoningGuidanceRule',
    description: 'Provides meta-level reasoning guidance',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.65,
    schema: MetaReasoningSchema,
    fallback: symbolicFallbacks['lm-meta-reasoning'],
    maxOutputTokens: 64,
  },
  {
    id: 'lm-uncertainty-calibration',
    prompt: 'For "{{primaryTerm}}", what confidence level is appropriate?',
    name: 'LMUncertaintyCalibrationRule',
    description: 'Calibrates uncertainty in beliefs',
    priority: 0.7,
    taskType: 'belief',
    budget: 0.6,
    schema: UncertaintySchema,
    fallback: symbolicFallbacks['lm-uncertainty-calibration'],
    maxOutputTokens: 64,
  },
  {
    id: 'lm-schema-induction',
    prompt: 'From "{{primaryTerm}}", what schema can be induced?',
    name: 'LMSchemaInductionRule',
    description: 'Induces schemas from examples',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.65,
    schema: SchemaInductionSchema,
    fallback: symbolicFallbacks['lm-schema-induction'],
    maxOutputTokens: 256,
  },
  {
    id: 'lm-temporal-causal',
    prompt: 'What temporal/causal relationships involve "{{primaryTerm}}"?',
    name: 'LMTemporalCausalModelingRule',
    description: 'Models temporal and causal relationships',
    priority: 0.8,
    taskType: 'belief',
    budget: 0.7,
    schema: TemporalCausalSchema,
    fallback: symbolicFallbacks['lm-temporal-causal'],
    maxOutputTokens: 128,
  },
  {
    id: 'lm-variable-grounding',
    prompt: 'What concrete instances ground "{{primaryTerm}}"?',
    name: 'LMVariableGroundingRule',
    description: 'Grounds variables in concrete instances',
    priority: 0.7,
    taskType: 'belief',
    budget: 0.65,
    activationCondition: (p) => hasVariable(p),
    schema: VariableGroundingSchema,
    fallback: symbolicFallbacks['lm-variable-grounding'],
    maxOutputTokens: 128,
  },
  {
    id: 'lm-concept-elaboration',
    prompt: 'Elaborate on "{{primaryTerm}}". What are its properties?',
    name: 'LMConceptElaborationRule',
    description: 'Elaborates on concept properties',
    priority: 0.75,
    taskType: 'belief',
    budget: 0.7,
    activationCondition: isUnderconnected,
    schema: ConceptElaborationSchema,
    fallback: symbolicFallbacks['lm-concept-elaboration'],
    maxOutputTokens: 256,
  },
];
