import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { tool } from 'ai';
import * as fc from 'fast-check';
import { z } from 'zod';

// --- generate_tests ---

export interface TestGenDeps {
  workspaceRoot?: string;
}

const toolSpecArbitrary = fc.record({
  name: fc.string({ minLength: 1, maxLength: 50 }),
  description: fc.string({ minLength: 1, maxLength: 200 }),
  inputSchema: fc.dictionary(fc.string(), fc.jsonValue()),
});

const connectionConfigArbitrary = fc.record({
  id: fc.string({ minLength: 1, maxLength: 50 }),
  enabled: fc.boolean(),
  type: fc.oneof(
    fc.constant('cli'),
    fc.constant('irc'),
    fc.constant('ws'),
    fc.constant('http'),
    fc.constant('mcp')
  ),
  config: fc.dictionary(fc.string(), fc.jsonValue()),
  authSecret: fc.option(fc.string({ maxLength: 100 }), { nil: undefined }),
});

const agentOptionsArbitrary = fc.record({
  nar: fc.option(fc.anything(), { nil: undefined }),
  lmService: fc.option(fc.anything(), { nil: undefined }),
  episodicMemory: fc.option(fc.anything(), { nil: undefined }),
  systemInstructions: fc.option(fc.string({ minLength: 1, maxLength: 1000 }), { nil: undefined }),
  context: fc.option(
    fc.record({
      attention: fc.oneof(fc.boolean(), fc.array(fc.string())),
      beliefs: fc.oneof(fc.boolean(), fc.array(fc.string())),
      goals: fc.oneof(fc.boolean(), fc.array(fc.string())),
      questions: fc.oneof(fc.boolean(), fc.array(fc.string())),
      concepts: fc.oneof(fc.boolean(), fc.array(fc.string())),
      maxItems: fc.option(fc.nat({ max: 100 }), { nil: undefined }),
      recency: fc.option(fc.nat({ max: 10000 }), { nil: undefined }),
    }),
    { nil: undefined }
  ),
  maxLoops: fc.nat({ max: 50 }),
  logger: fc.option(fc.anything(), { nil: undefined }),
  persistKnowledge: fc.boolean(),
  knowledgePath: fc.string({ minLength: 1, maxLength: 200 }),
  workspaceRoot: fc.option(fc.string({ minLength: 1, maxLength: 200 }), { nil: undefined }),
  externalTools: fc.option(fc.anything(), { nil: undefined }),
  approvalManager: fc.option(fc.anything(), { nil: undefined }),
  autonomyEngine: fc.option(fc.anything(), { nil: undefined }),
  reasoningIntervalMs: fc.option(fc.nat({ max: 3600000 }), { nil: undefined }),
  sessionHistoryLimit: fc.option(fc.nat({ max: 1000 }), { nil: undefined }),
  rateLimitPerMinute: fc.option(fc.nat({ max: 1000 }), { nil: undefined }),
  enableNlTranslation: fc.boolean(),
  enableNarseseHumanization: fc.boolean(),
});

const arbitraries: Record<string, fc.Arbitrary<unknown>> = {
  ToolSpec: toolSpecArbitrary,
  ConnectionConfig: connectionConfigArbitrary,
  AgentOptions: agentOptionsArbitrary,
};

function generateTestContent(schemaName: string, samples: unknown[]): string {
  const lines = [
    '// @generated by generate-tests tool',
    `// Schema: ${schemaName}`,
    `// Generated at: ${new Date().toISOString()}`,
    '',
    `import { describe, it, expect } from 'vitest';`,
    `import { ${schemaName}Schema } from '@senars/nar/tools/schemas';`,
    '',
    `describe('${schemaName} property tests', () => {`,
  ];

  for (let i = 0; i < samples.length; i++) {
    const sample = samples[i];
    const sampleStr = JSON.stringify(sample, null, 2);
    lines.push(`  it('sample ${i + 1}', () => {`);
    lines.push(`    const input = ${sampleStr};`);
    lines.push(`    const result = ${schemaName}Schema.safeParse(input);`);
    lines.push(`    expect(result.success).toBe(true);`);
    lines.push(`  });`);

    // Also test with an invalid mutation (wrong type for a known field)
    if (typeof sample === 'object' && sample !== null) {
      const mutated = { ...(sample as Record<string, unknown>) };
      // Add type violations based on schema
      if (schemaName === 'ToolSpec') {
        mutated.name = 123; // should be string
      } else if (schemaName === 'ConnectionConfig') {
        mutated.id = 123; // should be string
      } else if (schemaName === 'AgentOptions') {
        mutated.maxLoops = 'not a number'; // should be number
      }
      const mutatedStr = JSON.stringify(mutated, null, 2);
      lines.push(`  it('mutated sample ${i + 1} should fail (wrong type)', () => {`);
      lines.push(`    const input = ${mutatedStr};`);
      lines.push(`    const result = ${schemaName}Schema.safeParse(input);`);
      lines.push(`    expect(result.success).toBe(false);`);
      lines.push(`  });`);
    }
  }

  lines.push('});');
  lines.push('');
  return lines.join('\n');
}

export function createTestGenTools(deps: TestGenDeps = {}) {
  const workspaceRoot = deps.workspaceRoot || process.cwd();
  const generatedDir = resolve(workspaceRoot, 'tests/generated');

  return {
    generate_tests: tool({
      description:
        'Generate property-based tests from Zod schemas using fast-check. Creates test files in tests/generated/.',
      inputSchema: z.object({
        schemaName: z
          .enum(['ToolSpec', 'ConnectionConfig', 'AgentOptions'])
          .describe('Name of the schema to generate tests for'),
        sampleCount: z
          .number()
          .int()
          .min(1)
          .max(100)
          .optional()
          .default(10)
          .describe('Number of test samples to generate'),
        outputPath: z
          .string()
          .optional()
          .describe('Custom output path (relative to tests/generated/)'),
      }),
      execute: async ({ schemaName, sampleCount = 10, outputPath }) => {
        const arbitrary = arbitraries[schemaName];
        if (!arbitrary) {
          return { error: `Unknown schema: ${schemaName}`, generated: 0 };
        }

        try {
          const samples = fc.sample(arbitrary, sampleCount);

          const testContent = generateTestContent(schemaName, samples);

          await mkdir(generatedDir, { recursive: true });

          const fileName = outputPath || `${schemaName.toLowerCase()}.test.ts`;
          const filePath = resolve(generatedDir, fileName);
          await writeFile(filePath, testContent, 'utf-8');

          return {
            success: true,
            schema: schemaName,
            samplesGenerated: samples.length,
            outputFile: filePath,
            relativePath: `tests/generated/${fileName}`,
          };
        } catch (error) {
          return { error: String(error), generated: 0 };
        }
      },
    }),
  };
}
