export type Capability =
  // NAL reasoning
  | 'inheritance'
  | 'implication'
  | 'prediction'
  | 'retrospection'
  | 'conjunction'
  | 'disjunction'
  | 'negation'
  | 'abduction'
  | 'deduction'
  | 'induction'
  | 'analogy'
  | 'truth-revision'
  // MeTTa-style
  | 'pattern-match'
  | 'rewrite'
  | 'query'
  | 'multi-space'
  | 'skill-execution'
  // Memory
  | 'episodic-memory'
  | 'long-term-memory'
  | 'working-memory'
  // Drives/Goals
  | 'drive-management'
  | 'goal-management'
  // Meta
  | 'self-reasoning'
  | 'autonomy-loop'
  // External
  | 'tool-use'
  | 'llm-completion'
  | 'sql-query'
  | 'http-request';
